# Add a YAML file like this to the hidden config directory:
# $HOME/.fromtemplate/config.yaml


# Dictionary of template fields.
# Key = template field string; value = substitution
fields:
    __USER_NAME__: "YOUR NAME"
    __USER_EMAIL__: "your@email.com"
    # OTHER FIELDS...


# Dictionary of template files.
# Key = file suffix; value = absolute path to template file.
# The templates could be located anywhere, but the 
# hidden config directory  
# (i.e., /home/USERNAME/.fromtemplate/) 
# may be a convenient location to use.
templates: 
    #py: "/home/USERNAME/.fromtemplate/python_script/__FILE_NAME__.py"
    #sh: "/home/USERNAME/.fromtemplate/bash_script/__FILE_NAME__.sh"


